# Generated by Django 3.2 on 2021-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='postest_grade',
            field=models.IntegerField(blank=True, help_text='this grade is presented as percentage'),
        ),
    ]
