# Generated by Django 3.2 on 2021-05-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0003_question_question_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_num',
        ),
    ]
