# Generated by Django 3.2 on 2021-05-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0004_remove_question_question_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionB',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionD',
            field=models.CharField(max_length=100),
        ),
    ]
