# Generated by Django 3.2 on 2021-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0006_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(help_text='if no topic put N/A', max_length=100)),
                ('duration', models.IntegerField(help_text='input time takes to complete training in mins')),
                ('img', models.ImageField(upload_to='media/')),
                ('ppt', models.CharField(help_text='enter link to ppt in Onedrive', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(help_text='if no topic put N/A', max_length=100)),
                ('duration', models.IntegerField(help_text='input time takes to complete training in mins')),
                ('img', models.ImageField(upload_to='media/')),
                ('video_link', models.CharField(help_text='enter link to youtube video', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
