# Generated by Django 3.2.2 on 2021-05-15 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homecare', '0008_auto_20210509_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module_number', models.IntegerField(help_text='enter the number of module')),
            ],
        ),
        migrations.CreateModel(
            name='TestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretest_1_completion', models.BooleanField(default=False)),
                ('postest_1_completion', models.BooleanField(default=False)),
                ('pretest_2_completion', models.BooleanField(default=False)),
                ('postest_2_completion', models.BooleanField(default=False)),
                ('pretest_3_completion', models.BooleanField(default=False)),
                ('postest_3_completion', models.BooleanField(default=False)),
                ('pretest_4_completion', models.BooleanField(default=False)),
                ('postest_4_completion', models.BooleanField(default=False)),
                ('pretest_5_completion', models.BooleanField(default=False)),
                ('postest_5_completion', models.BooleanField(default=False)),
                ('pretest_6_completion', models.BooleanField(default=False)),
                ('postest_6_completion', models.BooleanField(default=False)),
                ('pretest_7_completion', models.BooleanField(default=False)),
                ('postest_7_completion', models.BooleanField(default=False)),
                ('pretest_8_completion', models.BooleanField(default=False)),
                ('postest_8_completion', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='homeslides',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainingppt',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='modules_completed',
            field=models.ManyToManyField(to='homecare.Module'),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homecare.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homecare.module'),
            preserve_default=False,
        ),
    ]
