# Generated by Django 3.2 on 2021-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0008_auto_20210509_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslides',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainingppt',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
