# Generated by Django 3.2.2 on 2021-05-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0009_auto_20210515_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcompletion',
            name='postest_1_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_2_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_3_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_4_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_5_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_6_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_7_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='postest_8_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_1_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_2_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_3_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_4_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_5_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_6_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_7_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testcompletion',
            name='pretest_8_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
