# Generated by Django 3.2.2 on 2021-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0011_auto_20210516_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomplete',
            name='test_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
