# Generated by Django 3.2.2 on 2021-05-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0012_alter_testcomplete_test_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomplete',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homecare.test'),
        ),
    ]
