# Generated by Django 3.2.2 on 2021-05-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0013_alter_testcomplete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcomplete',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homecare.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcomplete',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homecare.test'),
            preserve_default=False,
        ),
    ]
