# Generated by Django 3.2.2 on 2021-05-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0014_auto_20210516_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecompletion',
            old_name='modules_completed',
            new_name='modules',
        ),
    ]
