# Generated by Django 3.2.2 on 2021-05-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0016_auto_20210518_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attempts', models.IntegerField(help_text='set the value to 0.')),
                ('Difficulty', models.CharField(help_text='options are: easy, medium, difficult,N/A', max_length=100)),
                ('num_questions', models.IntegerField(help_text='enter the number of questions')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecare.module')),
            ],
            options={
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TrainingVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(help_text='if no topic put N/A', max_length=100)),
                ('duration', models.IntegerField(help_text='input time takes to complete training in mins')),
                ('img', models.ImageField(upload_to='images/')),
                ('video_link', models.CharField(help_text='enter link to youtube video', max_length=300)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecare.module')),
            ],
            options={
                'verbose_name_plural': 'TrainingVideos',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='module',
        ),
        migrations.DeleteModel(
            name='TrainingVideo',
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecare.tests'),
        ),
        migrations.AlterField(
            model_name='testcomplete',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecare.tests'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
