# Generated by Django 3.2.2 on 2021-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0017_auto_20210518_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletion',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testcomplete',
            name='user_answers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
