# Generated by Django 3.2.2 on 2021-05-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0018_auto_20210519_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingppt',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homecare.module'),
            preserve_default=False,
        ),
    ]
