# Generated by Django 3.2.2 on 2021-05-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0019_trainingppt_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
