# Generated by Django 3.2 on 2021-05-05 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretest_completion', models.BooleanField(default=False)),
                ('postest_completion', models.BooleanField(default=False)),
                ('training_completion', models.BooleanField(default=False)),
                ('postest_grade', models.IntegerField(help_text='this grade is presented as percentage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
