# Generated by Django 3.2 on 2021-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0002_auto_20210504_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
